=== OlafSzewczak/XML/Lab3/Zad4/Zad4.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT nauka (rodzaje, rzeczowniki)>

        <!ELEMENT rodzaje (rodzaj,rodzaj,rodzaj)>
        <!ELEMENT rzeczowniki (rzeczownik, rzeczownik, rzeczownik, rzeczownik, rzeczownik, rzeczownik, rzeczownik, rzeczownik, rzeczownik)>

        <!ELEMENT  rodzaj (#PCDATA)>
        <!ELEMENT rzeczownik (nazwa, synonimy?)>

        <!ELEMENT nazwa (#PCDATA)>
        <!ELEMENT synonimy (#PCDATA)>

        <!ATTLIST rodzaj skrot ("m", "z", "n") #REQUIRED>

=== OlafSzewczak/XML/Lab3/Zad4/Zad4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nauka SYSTEM "Zad4.dtd">

<nauka>

    <rodzaje>
        <rodzaj skrot="m">męski</rodzaj>
        <rodzaj skrot="z">żeński</rodzaj>
        <rodzaj skrot="n">nijaki</rodzaj>
    </rodzaje>
    <rzeczowniki>
        <rzeczownik>
            <nazwa>Kwiat</nazwa>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Kawa</nazwa>
            <synonimy>Kawusia Neska</synonimy>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Lekarz</nazwa>
            <synonimy>Doktor Medyk</synonimy>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Okno</nazwa>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Ziemia</nazwa>
            <synonimy>Grunt Gleba Rola</synonimy>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Ziarno</nazwa>
            <synonimy>Nasienie</synonimy>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Zwierzę</nazwa>
            <synonimy>Bestia Stworzenie</synonimy>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Dziupla</nazwa>
        </rzeczownik>
        <rzeczownik>
            <nazwa>Pies</nazwa>
        </rzeczownik>
    </rzeczowniki>

</nauka>
